### ISSUE TITLE
Error getting data key: 0 successful groups required, got 0

### ISSUE THREAD

**Issue by rsmets** [camptocamp/docker-argocd#7]
Upon following the README steps very closely I am seemingly stuck on retrieving the key for KMS from within argo. I am trying to deploy a custom chart.

I have added the following to my argocd's chart values.yaml. 
```
repoServer:
  env:
    - name: "AWS_ACCESS_KEY_ID"
      valueFrom:
        secretKeyRef:
          name: "argocd-secret"
          key: "aws.accessKeyId"
    - name: "AWS_SECRET_ACCESS_KEY"
      valueFrom:
        secretKeyRef:
          name: "argocd-secret"
          key: "aws.secretAccessKey"
```

I have also encrypted a secrets.yaml file in the argocd chart with the following format: 
```
configs:
  secret:
    extra:
      aws.accessKeyId: <Access Key ID>
      aws.secretAccessKey: <Secret Access Key>
```

I have installed `helm-sops` locally and I have tested decrypting and encrypting with the IAM user which those AWS access creds relate to. The output of `helm-sops template ...` on my host machine properly handles decrypting the secrets.yaml file of the target chart I am trying to use. 

The error seems to point towards not being able to retrieve the KMS key from within the argo-server (which was deployed with the argocd chart with the special configs mentioned above).

Upon inspection of the `argocd-repo-server` pod (created as a result on the chart install) I actually do not see the env var `AWS_ACCESS_KEY_ID` or `AWS_SECRET_ACCESS_KEY`. I feel like I should? i.e. the results of `kubectl exec -n argocd argocd-repo-server-64bf999468-ls6m9 -- printenv` does not yield the vars above.
