### ISSUE TITLE
Support new argocd version 2.0.x

### ISSUE THREAD

**Issue by tanandy** [camptocamp/docker-argocd#8]
Seems the wrapper is not compatible with the latest ArgoCD version because the repo-server will be a symlink to argocd binary in 1.9.x / 2.0.x

**Comment by yann-soubeyrand** [comment]
Could you explain why the wrapper won’t work anymore? I don’t see what will break but I didn’t test it though ;-)

However, maybe we could just replace the symlink with the wrapper to simlify the setup.

**Comment by tanandy** [comment]
Hi, i tested it. in the new argocd version, argocd repo bin is not a different binary anymore that is different from 1.8 and then argocd server == argocd repo server .... thats the reason why the wrapper doesnt work because the all in one binary doesnt work with this wrapper.

**Comment by m-yosefpor** [comment]
Yeah argocd-repo-server is a symbolic link in new argocd (1.9 and v2). So when `_argocd-repo-server` is called, `$0` arg is not one of the commands known to `argocd` binary. But it can be simply fixed by adding an env var:
```
ARGOCD_BINARY_NAME=argocd-repo-server
```

It is fixed by https://github.com/camptocamp/docker-argocd/pull/9

**Comment by gogovan-vincentngai** [comment]
Dont know why somehow seems not working ?
I added the env under repo-server section 

But it still turn to CrashLoopBackOff and [FATAL tini (7)] exec argocd-repo-server failed: Permission denied


**Dockerfile**
```
FROM golang:1.16 as builder
RUN git clone --branch=20200403-1 --depth=1 https://github.com/camptocamp/helm-sops && \
    cd helm-sops && \
    go build

FROM argoproj/argocd:v2.0.0
USER root
COPY argocd-repo-server-wrapper /usr/local/bin/
COPY --from=builder /go/helm-sops/helm-sops /usr/local/bin/
RUN cd /usr/local/bin && \
    mv argocd-repo-server _argocd-repo-server && \
    mv argocd-repo-server-wrapper argocd-repo-server && \
    mv helm _helm && \
    mv helm2 _helm2 && \
    mv helm-sops helm && \
    ln helm helm2
USER argocd
```

**argocd-repo-server-wrapper**
```
#! /bin/sh

GPG_PRIVATE_KEY_FILE='/app/config/gpg/privkey.asc'

if [ -f "${GPG_PRIVATE_KEY_FILE}" ]
then
	gpg --import "${GPG_PRIVATE_KEY_FILE}"
fi

exec "$(dirname "$0")/_$(basename "$0")" "$@"
```

I am using yaml to deploy my argocd ...

```
piVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: repo-server
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/part-of: argocd
  name: argocd-repo-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-repo-server
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: argocd-repo-server
              topologyKey: kubernetes.io/hostname
            weight: 100
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/part-of: argocd
              topologyKey: kubernetes.io/hostname
            weight: 5
      automountServiceAccountToken: false
      containers:
      - command:
        - uid_entrypoint.sh
        - argocd-repo-server
        - --redis
        - argocd-redis:6379
        image: mypatched_images
        env:
        - name: ARGOCD_BINARY_NAME
          value: "argocd-repo-server"
        imagePullPolicy: Always
....
```
